### ISSUE TITLE
¿Cuando filtras por años no será bueno notificar al usuario?

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#101]
P. ej. decirle "Se filtraron los resultados por la fecha 2015-04"

Lo comento porque como la tabla está muy abajo, parece que le picas a los cuadros y no sucede nada.

**Comment by chuckcfs** [comment]
¿agregamos un mensaje arriba?

**Comment by rodowi** [comment]
me gusta la idea de un mensaje arriba, porque es menos destructivo

**Comment by chuckcfs** [comment]
hecho
