### ISSUE TITLE
Como usuario puedo descargar en CSV la vista actual del mapa

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#13]

**Comment by rodowi** [comment]
La solución más fácil es que el botón de descarga baje todo el CSV que tenemos en drive

pero en el largo plazo tenemos que hacer que se publiquen en datos.gob.mx

**Comment by chuckcfs** [comment]
@rodowi todos los datos de la tabla o de la base de datos?

**Comment by rodowi** [comment]
lo más fácil es el archivo completo no? por que descargar una parte implicaría que BUDA tuviera un endpoint csv

**Comment by chuckcfs** [comment]
no necesariamente, podríamos crear el CSV desde el front para la búsqueda actual o algo por el estilo

**Comment by rodowi** [comment]
si se puede crear el CSV en el front, pues a darle así
