### ISSUE TITLE
Como usuario puedo ver las obras de reconstrucción relacionadas a una declaratoria de desastre

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#15]

**Comment by rodowi** [comment]
Las imágenes serán cargadas a S3 por @eduardoclark

**Comment by chuckcfs** [comment]
para esto nos falta el campo para relacionar una declaratoria de desastre con las de reconstrucción

**Comment by rodowi** [comment]
por lo pronto usemos la pestaña extra como mencionas
