### ISSUE TITLE
Agregar tooltip a la infografía de FONDEN

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#36]
FONDEN emergencias

Texto del cuadro  | Texto para tooltip
----------------------- | ---------------------
Hidrometeorológicos  | a)    Tormenta tropical; b)    Huracán; c)    Vientos fuertes; d)    Lluvia severa; e)    Nevada severa; f)     Granizada severa; g)    Helada severa; h)    Inundación fluvial; i)      Inundación pluvial, y j)     Tornado.
Geológicos  | a) Alud; b)    Erupción volcánica; c)    Hundimiento; d)    Maremoto; e)    Movimiento de ladera; f)     Ola extrema; g)    Sismo, y h)    Subsidencia.
Otros  | · Marea roja · Riesgos químicos y tecnológicos
Solicita el Dictamen de Corroboración  | CNPC se refiere a la Coordinación Nacional de Protección Civil, la cual coordina el Sistema Nacional de Protección Civil, es decir, las acciones destinadas a la protección contra los peligros que se presenten y a la recuperación de la población, en la eventualidad de un desastre que se coordinan entre las dependencias y entidades del sector público, diversos grupos voluntarios, y las autoridades de los gobiernos locales.
Solicita la declaratoria de emergencia y describe la situación actual de la población ante la emergencia | Para solicitar la declaratoria de emergencia, la entidad federativa llena el formato “A”. Asimismo, describe la situación actual de la población a través del formato “B”, los cuales se encuentran disponibles en http://www.proteccioncivil.gob.mx/es/ProteccionCivil/Normatividad
Realiza el Dictamen de Corroboración del fenómeno natural perturbador | Las Instancias Técnicas Facultadas por tipo de fenómeno son las siguientes: ·         Hidrometeorológicos: la Comisión Nacional del Agua (CONAGUA) ·         Incendios forestales: la Comisión Nacional Forestal (CONAFOR) ·         Geológicos: el Centro Nacional de Prevención de Desastres (CENAPRED)
Gestiona el suministro de insumos y emite reporte con estimaciones de población vulnerable afectada | La Secretaría de Gobernación, a través de la Dirección General de Recursos Materiales y Servicios Generales, así como la Dirección General de Protección Civil.
Solicita los insumos (consumibles, duraderos y servicios) para la atención de la población afectada (hasta por 4 días) | Para solicitar los insumos, la entidad federativa llena el formato “C” disponible en http://www.proteccioncivil.gob.mx/es/ProteccionCivil/Normatividad Algunos ejemplos de insumos son: ·         Despensas alimenticias ·         Agua ·         Artículos de abrigo y protección ·         Herramientas ·         Artículos de aseo personal ·         Arrendamiento de letrinas ·         Combustible
Solicita los medicamentos y elabora la minuta de sesión del Comité Estatal para la Seguridad en Salud | Para solicitar los medicamentos, la Secretaría de Salud de la entidad federativa llena el formato “F” disponible en http://www.proteccioncivil.gob.mx/es/ProteccionCivil/Normatividad
Valida la solicitud de medicamentos | La Secretaría de Salud Federal
Publicación en el DOF de la declaratoria de emergencia | Consulta un ejemplo de declaratoria en http://www.dof.gob.mx/nota_detalle.php?codigo=5391763&fecha=12/05/2015
Recibe Insumos: Encuesta de satisfacción | La encuesta de satisfacción que se debe aplicar se encuentra disponible en el formato “D” de la página http://www.proteccioncivil.gob.mx/es/ProteccionCivil/Normatividad
Publica el informe de utilización de insumos y medicamentos en internet | Consulta los informes de utilización de insumos para 2015 en http://www.proteccioncivil.gob.mx/en/ProteccionCivil/2015

**Comment by rodowi** [comment]
FONDEN infraestructura

Texto del cuadro | Texto para tooltip
|-----|------|
Hidrometeorológicos  | a)    Tormenta tropical; b)    Huracán; c)    Vientos fuertes; d)    Lluvia severa; e)    Nevada severa; f)     Granizada severa; g)    Helada severa; h)    Inundación fluvial; i)      Inundación pluvial, y j)     Tornado.
Geológicos  | a) Alud; b)    Erupción volcánica; c)    Hundimiento; d)    Maremoto; e)    Movimiento de ladera; f)     Ola extrema; g)    Sismo, y h)    Subsidencia.
Otros  | · Marea roja · Riesgos químicos y tecnológicos
Emite dictamen de corroboración del fenómeno natural perturbador | Las Instancias Técnicas Facultadas por tipo de fenómeno son las siguientes: ·         Hidrometeorológicos: la Comisión Nacional del Agua (CONAGUA) ·         Incendios forestales: la Comisión Nacional Forestal (CONAFOR) ·         Geológicos: el Centro Nacional de Prevención de Desastres (CENAPRED)
Solicitud de la emisión de declaratoria de desastre natural | Ejemplo de la solicitud de la emisión de declaratoria de desastre natural disponible en http://www.proteccioncivil.gob.mx/work/models/ProteccionCivil/Resource/32/12/images/Formato-Solicitud-de-Declaratoria-de-Desastre-Natural.pdf
Solicitud de APIN | Solicitud de Apoyos Parciales Inmediatos, es decir, recursos para la ejecución de acciones emergentes, así como los trabajos y obras de carácter prioritario y urgente, dirigidas a solventar la situación crítica del desastre natural, tales como el restablecimiento de las comunicaciones, los servicios básicos, la limpieza inmediata, remoción de escombros y todo aquello que coadyuve a la normalización de la actividad de la zona afectada, así como para evitar mayores daños y proteger a la población.
Publicación en el DOF de la declaratoria de emergencia | Consulta un ejemplo de declaratoria en http://www.dof.gob.mx/nota_detalle.php?codigo=5391763&fecha=12/05/2015
Entrega de resultados del Comité de Evaluación de Daños, incluyendo el diagnóstico (preliminar) | El diagnóstico preliminar se realiza a través de un formato, disponible en http://www.proteccioncivil.gob.mx/work/models/ProteccionCivil/Resource/32/12/images/Formato-Diagnostico-Preliminar-de-Obras-y-Acciones.pdf
Solicitud integral de recursos | La Secretaría de Gobernación, a través de la Dirección General para la Gestión de Riesgos realiza la solicitud de recursos a la Secretaría de Hacienda y Crédito Público.
Autoriza los recursos con cargo al FONDEN | Puede ser con cargo al programa FONDEN o al fideicomiso FONDEN. Conoce los recursos autorizados por declaratoria de desastre en http://www.proteccioncivil.gob.mx/es/ProteccionCivil/Recursos_Autorizados_por_Declaratoria_de_Desastre

**Comment by chuckcfs** [comment]
tooltip? todo eso en un tooltip?? :scream: @rodowi
