### ISSUE TITLE
Activar http://mxabierto.github.io/fonden

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#39]
Creo que nos falta un build en gh-pages

**Comment by rodowi** [comment]
➜  fonden git:(master) grunt deploy
Warning: Task "deploy" not found. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-07-21 01:12:02 UTC)
loading tasks  261ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 262ms

**Comment by chuckcfs** [comment]
Es que el comando es `grunt publish` si lo haces desde un clon de mxabierto hace el branch y todo
