### ISSUE TITLE
Falta la infografía de Declaratoria de Emergencias

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#48]
La actual es la de Declaratoria de Desastres.

**Comment by chuckcfs** [comment]
@rodowi ¿la pongo abajo de la que estas?

**Comment by rodowi** [comment]
Tabs mejor no? para que no sea tanto scroll vertical

#IMHO

**Comment by chuckcfs** [comment]
vale

**Comment by chuckcfs** [comment]
@rodowi no esta en el drive, sólo esta en PDF
