### ISSUE TITLE
Agregamos un correo de contacto en ¿Qué es el FONDEN?

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#49]

**Comment by chuckcfs** [comment]
@rodowi en donde lo agrego, y, ¿que correo?

**Comment by rodowi** [comment]
Preguntaré esto en slack.

**Comment by rodowi** [comment]
comunicacion@datos.gob.mx al final con una línea:

"¿Tienes alguna pregunta que no está incluida? Escríbenos a comunicacion@datos.gob.mx"
