### ISSUE TITLE
Filtro de texto por Estados también

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#50]
El filtro ya funciona con el título de la declaratoria, pero también sería intuitivo permitir el filtro por el nombre del Estado

![screen shot 2015-07-27 at 4 22 06 pm](https://cloud.githubusercontent.com/assets/705860/8918125/c3808f5e-347b-11e5-8029-25490ffff82b.png)

**Comment by chuckcfs** [comment]
@rodowi el filtro por estado es el mapa, y es que esa caja no es para filtrar, en cuanto este la funcionlidad en el backend será para búsquedas

**Comment by rodowi** [comment]
ok, mi punto aquí es que dejemos claro para qué sirve la caja, si para encontrar por título, o por "título o estado".

**Comment by chuckcfs** [comment]
ok, le agrego un placeholder? algo así como `Búsqueda por titulo...`

**Comment by rodowi** [comment]
sí por fa
