### ISSUE TITLE
La barra de tiempo debería traer resultados de esas fechas, no filtrar la tabla actual?

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#53]
Esta es duda de UX.

En general creo que los "filtros" actuales, tanto de tiempo como texto, deberían buscar en toda la base, no en los 20 resultados que se ven ahorita.

**Comment by chuckcfs** [comment]
@rodowi si, esa es la intención, pero en este momento BUDA no tiene soporte aún para búsquedas por rango

**Comment by rodowi** [comment]
lo entiendo, por eso está en backlog este issue

**Comment by rodowi** [comment]
ya abrí issue en buda https://github.com/mxabierto/buda/issues/21

**Comment by chuckcfs** [comment]
va que va
