### ISSUE TITLE
Vista de detalle de las declaratorias no carga

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#78]
Intenté ver una declaratoria y la tabla se queda vacía, p. ej. http://fonden.datos.gob.mx/#/explora-el-fonden/Lluvia%20severa%20los%20d%C3%ADas%2015%20y%2016%20de%20marzo%20en%2015%20municipios

**Comment by chuckcfs** [comment]
eso es porque de "Desastres" no hay vista de detalles, en reconstrucción son las obras y en emergencias son los bienes entregados, pero en "Desastres" no hay diseño ni nada
