### ISSUE TITLE
La infografía de FONDEN emergencias no es la última versión enviada. Se adjuta de nuevo la última versión para mayor referencia

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#93]
Está en el mismo drive.

Tienen como sufijo el timestamp del día de hoy.

**Comment by chuckcfs** [comment]
@rodowi esa infografía esta mal, no esta optimizada (son 4MB) ni incluye la fuente que es, dile a Diego, él en las otras las ya había hecho esos cambios
