### ISSUE TITLE
Al desactivar la primera capa de cualquiera de las pestañas del mapa (Desastres, Emergencias o Reconstrucción) no ocurre nada. Las otras capas funcionan correctamente, pero la primera sigue coloreando los estados

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#95]
Las otras capas funcionan correctamente, pero la primera sigue coloreando los estados

**Comment by rodowi** [comment]
Creo que puede ser cuestión de simplemente desactivar la interacción en esa celda. Ya que siempre queremos que los estados estén pintados no @chuckcfs ?

**Comment by chuckcfs** [comment]
@rodowi creo que sí, no tiene caso un mapa vacio
