### ISSUE TITLE
Si ya se seleccionó algún rubro de la parte de abajo del mapa, ya no es posible regresar.

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#96]
Es un tema de UX, ya que el breadcrumb está arriba.

Deberíamos hacer scroll-up, o tener un breadcrumb también a nivel de la tabla de resultados?

**Comment by chuckcfs** [comment]
este no lo entiendo :scream:

**Comment by rodowi** [comment]
creo que se refieren a cuando das click en alguna declaratoria (en la tabla). Lo que vi fue que como se carga la tabla en esa misma posición Y, no se alcanza a ver el breadcrumb, y parece que no puedes regresar

**Comment by chuckcfs** [comment]
ah ok, ¿quieres que haga un scroll a 0 como en las otras páginas?

**Comment by chuckcfs** [comment]
un segundo breadcrumb se me hace demasiado ¿no?

**Comment by rodowi** [comment]
probemos con el scroll a 0,

no nos gusta duplicar cosas

**Comment by chuckcfs** [comment]
hecho
