### ISSUE TITLE
7.       El filtro por título que está debajo del mapa al parecer no está funcionando.

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#97]

**Comment by chuckcfs** [comment]
ese no es un filtro, es una caja de búsqueda

**Comment by chuckcfs** [comment]
pero ya vi, lo checo

**Comment by chuckcfs** [comment]
e igual con el último publish funciona correctamente

<img width="1160" alt="screen shot 2015-08-28 at 13 46 24" src="https://cloud.githubusercontent.com/assets/1383865/9554410/3ef1de22-4d8b-11e5-8091-b27ed398a445.png">

**Comment by rodowi** [comment]
awesome nomás liguemos este issue a un PR

**Comment by chuckcfs** [comment]
se resolvio en el PR #90 , no se como ligarlo ya que esta cerrado
