### ISSUE TITLE
8.       La descarga de csv no respeta los filtros aplicados.

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#98]
Tal vez es cuestión de hacer explícito que el botón DESCARGA TODOS LOS DATOS

**Comment by rodowi** [comment]
hey @chuckcfs queremos que se descarguen datos filtrados, o que se descargue toda la base?

en lo personal odio cuando las bases no vienen completas.

yo preferiría un DESCARGA TODOS LOS DATOS

**Comment by chuckcfs** [comment]
pues si no se ponen filtros se baja toda la base, pero si alguien esta filtrando creo que si hace sentido que se baje filtrado, y se bajan todos los que hacen match no nada más los de la primer página

**Comment by rodowi** [comment]
ok, go for it,

**Comment by rodowi** [comment]
cierto, creo que eso habíamos acordado entre todos hace tiempo

**Comment by chuckcfs** [comment]
hecho, ya esta el PR ahí, PR #102
