### ISSUE TITLE
9.       La barra para desplazarse entre páginas no muestra información distinta al avanzar en los números. Siempre muestra la primera pantalla:

### ISSUE THREAD

**Issue by rodowi** [mxabierto/fonden#99]
Parece que los requests no están saliendo

**Comment by chuckcfs** [comment]
esto era un issue que ya estaba resuelto, sólo faltaba hacer el push, ya quedo hecho

<img width="1178" alt="screen shot 2015-08-28 at 13 42 57" src="https://cloud.githubusercontent.com/assets/1383865/9554337/c150cbfe-4d8a-11e5-9b6e-68b343ff3f5c.png">

<img width="1174" alt="screen shot 2015-08-28 at 13 43 06" src="https://cloud.githubusercontent.com/assets/1383865/9554340/c3d2290e-4d8a-11e5-8947-04478a5aa562.png">

**Comment by rodowi** [comment]
En qué PR se resolvió?

**Comment by chuckcfs** [comment]
#90
